### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by vashian** [ahmadalibagheri/ansible-tutorial#9]
Running the initial command from [here](https://github.com/ahmadalibagheri/ansible-tutorial/tree/master/part00-getting-ready#initial-step):

```bash
ansible all -k -K -m authorized_key -a "user='your_username' state='present' key='{{lookup('file', ~/.ssh/id_rsa.pub)}}'"
```
caused I get an error and here's my error message:
```bash
template error while templating string: unexpected '~'. String: {{lookup('file', ~/.ssh/id_rsa.pub)}}
```

I think lookup plugin parameters need to be in quotes.

**Comment by ahmadalibagheri** [comment]
Thank you @vashian it's good, I've merged your PR and closed your issue. 

If you are happy, you can contribute on [bash repo ](https://github.com/ahmadalibagheri/bash-script-tutorial) and [Packer Repo](https://github.com/ahmadalibagheri/packer-tutorial).

 Thank you for your contribution.
